#!/bin/bash

# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.
my_external_monitor=$(xrandr --query | grep 'VGA')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output VGA-0 --mode 1920x1080 --rotate normal --right-of HDMI-0
fi
