#! /bin/bash


sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.dotfiles/bspwm/bspwm_dual_monitor ];then
    bash $HOME/.dotfiles/bspwm/bspwm_dual_monitor
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/bin/polybar ]; then
    bash $HOME/.dotfiles/bspwm/polybar_launch.sh
fi

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor VGA-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-scale ~/Bilder/aks-voidX-arcade.png &
